# Simple workflow for deploying static content to GitHub Pages
name: Build app

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
      
      - name: Build app
        run: msbuild hram.sln /p:configuration=Release /p:platform=x64

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: 'hram'
      #     path: 'x64/Release/hram.exe'

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload "${{ GITHUB_REF }}" "x64/Release/hram.exe"
