# Simple workflow for deploying static content to GitHub Pages
name: Build app

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
      
      - name: Build app
        run: msbuild hram.sln /p:configuration=Release /p:platform=x64

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'x64/Release/hram.exe'
